<?php

$DefaultFields = "
		@TOTAL_HARI_BULAN AS TOTAL_HARI_BULAN, @TOTAL_HARI_ABSEN AS TOTAL_HARI_ABSEN,
		@TOTAL_ABSEN_HADIR AS TOTAL_ABSEN_HADIR, @TOTAL_ABSEN_IZIN AS TOTAL_ABSEN_IZIN,
		@TOTAL_ABSEN_SAKIT AS TOTAL_ABSEN_SAKIT, @TOTAL_ABSEN_ALPHA AS TOTAL_ABSEN_ALPHA,
		ROUND(@TOTAL_ABSEN_HADIR / @TOTAL_HARI_ABSEN * 100) AS PERSENTASE_KEHADIRAN 

		";

if ($Fields) {
	$DefaultFields = $Fields;
}


$SQL = "
	SET @SELECTED_DAY = '{$SELECTED_DAY}';
	SET @NISN = '{$nisn}';

	SET @TOTAL_HARI_BULAN = (
	SELECT COUNT(a.Date)
	FROM (
	    SELECT LAST_DAY(@SELECTED_DAY) - INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY AS DATE
	    FROM (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS a
	    CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS b
	    CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS c
	) a 
	WHERE a.Date BETWEEN @SELECTED_DAY AND LAST_DAY(@SELECTED_DAY) ORDER BY a.Date
	);

	SET @TOTAL_HARI_ABSEN = @TOTAL_HARI_BULAN - (
		SELECT (CASE DAYOFMONTH(LAST_DAY(@SELECTED_DAY))
			WHEN 31 THEN
			    CASE DAYOFWEEK(LAST_DAY(@SELECTED_DAY))
				WHEN 1 THEN 5
				WHEN 2 THEN 5
				WHEN 3 THEN 5
				ELSE 4
			    END 
			WHEN 30 THEN
			    CASE DAYOFWEEK(LAST_DAY(@SELECTED_DAY))
				WHEN 1 THEN 5
				WHEN 2 THEN 5
				ELSE 4
			    END 
			WHEN 29 THEN
			    CASE DAYOFWEEK(LAST_DAY(@SELECTED_DAY))
				WHEN 1 THEN 5
				ELSE 4
			    END 
			ELSE 4
		    END) AS WEEK_END
	   );


	SET @TOTAL_ABSEN_HADIR = (
	SELECT COUNT(tanggal_absen) FROM `tbl_absen`
	WHERE nisn = @NISN AND tanggal_absen BETWEEN @SELECTED_DAY AND LAST_DAY(@SELECTED_DAY)
	AND tipe_absen = 1
	 ORDER BY tanggal_absen
	);

	SET @TOTAL_ABSEN_IZIN = (
	SELECT COUNT(tanggal_absen) FROM `tbl_absen`
	WHERE nisn = @NISN AND tanggal_absen BETWEEN @SELECTED_DAY AND LAST_DAY(@SELECTED_DAY)
	AND tipe_absen = 2
	 ORDER BY tanggal_absen
	);

	SET @TOTAL_ABSEN_SAKIT = (
	SELECT COUNT(tanggal_absen) FROM `tbl_absen`
	WHERE nisn = @NISN AND tanggal_absen BETWEEN @SELECTED_DAY AND LAST_DAY(@SELECTED_DAY)
	AND tipe_absen = 3
	 ORDER BY tanggal_absen
	);

	SET @TOTAL_ABSEN_ALPHA = (
	SELECT COUNT(tanggal_absen) FROM `tbl_absen`
	WHERE nisn = @NISN AND tanggal_absen BETWEEN @SELECTED_DAY AND LAST_DAY(@SELECTED_DAY)
	AND tipe_absen = 4
	 ORDER BY tanggal_absen
	);


	SELECT $DefaultFields

		";
